(IN-PACKAGE :PEPPOL/CODE-LISTS)

(DEFVAR |Charge reason code (UNCL7161)|
  '(("Advertising" . "AA") ("Telecommunication" . "AAA")
    ("Technical modification" . "AAC") ("Job-order production" . "AAD")
    ("Outlays" . "AAE") ("Off-premises" . "AAF")
    ("Additional processing" . "AAH") ("Attesting" . "AAI")
    ("Acceptance" . "AAS") ("Rush delivery" . "AAT")
    ("Special construction" . "AAV") ("Airport facilities" . "AAY")
    ("Concession" . "AAZ") ("Compulsory storage" . "ABA")
    ("Fuel removal" . "ABB") ("Into plane" . "ABC") ("Overtime" . "ABD")
    ("Tooling" . "ABF") ("Miscellaneous" . "ABK")
    ("Additional packaging" . "ABL") ("Dunnage" . "ABN")
    ("Containerisation" . "ABR") ("Carton packing" . "ABS")
    ("Hessian wrapped" . "ABT") ("Polyethylene wrap packing" . "ABU")
    ("Miscellaneous treatment" . "ACF") ("Enamelling treatment" . "ACG")
    ("Heat treatment" . "ACH") ("Plating treatment" . "ACI")
    ("Painting" . "ACJ") ("Polishing" . "ACK") ("Priming" . "ACL")
    ("Preservation treatment" . "ACM") ("Fitting" . "ACS")
    ("Consolidation" . "ADC") ("Bill of lading" . "ADE") ("Airbag" . "ADJ")
    ("Transfer" . "ADK") ("Slipsheet" . "ADL") ("Binding" . "ADM")
    ("Repair or replacement of broken returnable package" . "ADN")
    ("Efficient logistics" . "ADO") ("Merchandising" . "ADP")
    ("Product mix" . "ADQ") ("Other services" . "ADR") ("Pick-up" . "ADT")
    ("Chronic illness" . "ADW") ("New product introduction" . "ADY")
    ("Direct delivery" . "ADZ") ("Diversion" . "AEA") ("Disconnect" . "AEB")
    ("Distribution" . "AEC") ("Handling of hazardous cargo" . "AED")
    ("Rents and leases" . "AEF") ("Location differential" . "AEH")
    ("Aircraft refueling" . "AEI") ("Fuel shipped into storage" . "AEJ")
    ("Cash on delivery" . "AEK") ("Small order processing service" . "AEL")
    ("Clerical or administrative services" . "AEM") ("Guarantee" . "AEN")
    ("Collection and recycling" . "AEO") ("Copyright fee collection" . "AEP")
    ("Veterinary inspection service" . "AES") ("Pensioner service" . "AET")
    ("Medicine free pass holder" . "AEU")
    ("Environmental protection service" . "AEV")
    ("Environmental clean-up service" . "AEW")
    ("National cheque processing service outside account area" . "AEX")
    ("National payment service outside account area" . "AEY")
    ("National payment service within account area" . "AEZ")
    ("Adjustments" . "AJ") ("Authentication" . "AU") ("Cataloguing" . "CA")
    ("Cartage" . "CAB") ("Certification" . "CAD")
    ("Certificate of conformance" . "CAE") ("Certificate of origin" . "CAF")
    ("Cutting" . "CAI") ("Consular service" . "CAJ")
    ("Customer collection" . "CAK") ("Payroll payment service" . "CAL")
    ("Cash transportation" . "CAM") ("Home banking service" . "CAN")
    ("Bilateral agreement service" . "CAO")
    ("Insurance brokerage service" . "CAP") ("Cheque generation" . "CAQ")
    ("Preferential merchandising location" . "CAR") ("Crane" . "CAS")
    ("Special colour service" . "CAT") ("Sorting" . "CAU")
    ("Battery collection and recycling" . "CAV")
    ("Product take back fee" . "CAW") ("Car loading" . "CD")
    ("Cleaning" . "CG") ("Cigarette stamping" . "CS")
    ("Count and recount" . "CT") ("Layout/design" . "DAB")
    ("Driver assigned unloading" . "DAD") ("Delivery" . "DL")
    ("Engraving" . "EG") ("Expediting" . "EP")
    ("Exchange rate guarantee" . "ER") ("Fabrication" . "FAA")
    ("Freight equalization" . "FAB") ("Freight extraordinary handling" . "FAC")
    ("Freight service" . "FC") ("Filling/handling" . "FH") ("Financing" . "FI")
    ("Grinding" . "GAA") ("Hose" . "HAA") ("Handling" . "HD")
    ("Hoisting and hauling" . "HH") ("Installation" . "IAA")
    ("Installation and warranty" . "IAB") ("Inside delivery" . "ID")
    ("Inspection" . "IF") ("Installation and training" . "IR")
    ("Invoicing" . "IS") ("Koshering" . "KO") ("Carrier count" . "L1")
    ("Labelling" . "LA") ("Labour" . "LAA") ("Repair and return" . "LAB")
    ("Legalisation" . "LF") ("Mounting" . "MAE") ("Mail invoice" . "MI")
    ("Mail invoice to each location" . "ML")
    ("Non-returnable containers" . "NAA") ("Outside cable connectors" . "OA")
    ("Invoice with shipment" . "PA")
    ("Phosphatizing (steel treatment)" . "PAA") ("Packing" . "PC")
    ("Palletizing" . "PL") ("Repacking" . "RAB") ("Repair" . "RAC")
    ("Returnable container" . "RAD") ("Restocking" . "RAF")
    ("Re-delivery" . "RE") ("Refurbishing" . "RF") ("Rail wagon hire" . "RH")
    ("Loading" . "RV") ("Salvaging" . "SA") ("Shipping and handling" . "SAA")
    ("Special packaging" . "SAD") ("Stamping" . "SAE")
    ("Consignee unload" . "SAI") ("Shrink-wrap" . "SG")
    ("Special handling" . "SH") ("Special finish" . "SM") ("Set-up" . "SU")
    ("Tank renting" . "TAB") ("Testing" . "TAC")
    ("Transportation - third party billing" . "TT")
    ("Transportation by vendor" . "TV") ("Drop yard" . "V1")
    ("Drop dock" . "V2") ("Warehousing" . "WH")
    ("Combine all same day shipment" . "XAA") ("Split pick-up" . "YY")
    ("Mutually defined" . "ZZZ")))

(EXPORT '|Charge reason code (UNCL7161)| :PEPPOL/CODE-LISTS)