(IN-PACKAGE :PEPPOL/CODE-LISTS)

(DEFVAR |Electronic Address Scheme (EAS)|
  '(("System Information et Repertoire des Entreprise et des Etablissements: SIRENE"
     . "0002")
    ("Organisationsnummer (Swedish legal entities)" . "0007")
    ("SIRET-CODE" . "0009") ("LY-tunnus" . "0037")
    ("Data Universal Numbering System (D-U-N-S Number)" . "0060")
    ("EAN Location Code" . "0088")
    ("DANISH CHAMBER OF COMMERCE Scheme (EDIRA compliant)" . "0096")
    ("FTI - Ediforum Italia, (EDIRA compliant)" . "0097")
    ("\"Vereniging van Kamers van Koophandel en Fabrieken in Nederland (Association of
            Chambers of Commerce and Industry in the Netherlands), Scheme (EDIRA compliant)\""
     . "0106")
    ("Directorates of the European Commission" . "0130")
    ("SIA Object Identifiers" . "0135") ("SECETI Object Identifiers" . "0142")
    ("Australian Business Number (ABN) Scheme" . "0151")
    ("Numéro d'identification suisse des enterprises (IDE), Swiss Unique Business
            Identification Number (UIDB)"
     . "0183")
    ("DIGSTORG" . "0184") ("Dutch Originator's Identification Number" . "0190")
    ("Centre of Registers and Information Systems of the Ministry of Justice"
     . "0191")
    ("Enhetsregisteret ved Bronnoysundregisterne " . "0192")
    ("UBL.BE party identifier" . "0193") ("Singapore UEN identifier" . "0195")
    ("Kennitala - Iceland legal id for individuals and legal entities"
     . "0196")
    ("ERSTORG" . "0198") ("Legal Entity Identifier (LEI)" . "0199")
    ("Legal entity code (Lithuania)" . "0200")
    ("Codice Univoco Unità Organizzativa iPA" . "0201")
    ("Indirizzo di Posta Elettronica Certificata" . "0202")
    ("Leitweg-ID" . "0204")
    ("Numero d'entreprise / ondernemingsnummer / Unternehmensnummer" . "0208")
    ("Danish Ministry of the Interior and Health" . "9901")
    ("Ufficio responsabile gestione partite IVA" . "9906")
    ("TAX Authority" . "9907") ("Hungary VAT number" . "9910")
    ("Business Registers Network" . "9913")
    ("Österreichische Umsatzsteuer-Identifikationsnummer" . "9914")
    ("\"Österreichisches Verwaltungs bzw. Organisationskennzeichen\"" . "9915")
    ("\"SOCIETY FOR WORLDWIDE INTERBANK FINANCIAL, TELECOMMUNICATION S.W.I.F.T\""
     . "9918")
    ("Kennziffer des Unternehmensregisters " . "9919")
    ("Agencia Española de Administración Tributaria " . "9920")
    ("Andorra VAT number" . "9922") ("Albania VAT number" . "9923")
    ("Bosnia and Herzegovina VAT number" . "9924")
    ("Belgium VAT number" . "9925") ("Bulgaria VAT number" . "9926")
    ("Switzerland VAT number" . "9927") ("Cyprus VAT number" . "9928")
    ("Czech Republic VAT number" . "9929") ("Germany VAT number" . "9930")
    ("Estonia VAT number" . "9931") ("United Kingdom VAT number" . "9932")
    ("Greece VAT number" . "9933") ("Croatia VAT number" . "9934")
    ("Ireland VAT number" . "9935") ("Liechtenstein VAT number" . "9936")
    ("Lithuania VAT number" . "9937") ("Luxemburg VAT number" . "9938")
    ("Latvia VAT number" . "9939") ("Monaco VAT number" . "9940")
    ("Montenegro VAT number" . "9941")
    ("Macedonia, the former Yugoslav Republic of VAT number" . "9942")
    ("Malta VAT number" . "9943") ("Netherlands VAT number" . "9944")
    ("Poland VAT number" . "9945") ("Portugal VAT number" . "9946")
    ("Romania VAT number" . "9947") ("Serbia VAT number" . "9948")
    ("Slovenia VAT number" . "9949") ("Slovakia VAT number" . "9950")
    ("San Marino VAT number" . "9951") ("Turkey VAT number" . "9952")
    ("Holy See (Vatican City State) VAT number" . "9953")
    ("Swedish VAT number" . "9955")
    ("Belgian Crossroad Bank of Enterprises " . "9956")
    ("French VAT number" . "9957") ("German Leitweg ID" . "9958")))

(EXPORT '|Electronic Address Scheme (EAS)| :PEPPOL/CODE-LISTS)