(IN-PACKAGE :PEPPOL/CODE-LISTS)

(DEFVAR |Invoiced object identifier scheme (UNCL 1153)|
  '(("Order acknowledgement document identifier" . "AAA")
    ("Proforma invoice document identifier" . "AAB")
    ("Documentary credit identifier" . "AAC")
    ("Contract document addendum identifier" . "AAD")
    ("Goods declaration number" . "AAE") ("Debit card number" . "AAF")
    ("Offer number" . "AAG")
    ("Bank's batch interbank transaction reference number" . "AAH")
    ("Bank's individual interbank transaction reference number" . "AAI")
    ("Delivery order number" . "AAJ") ("Despatch advice number" . "AAK")
    ("Drawing number" . "AAL") ("Waybill number" . "AAM")
    ("Delivery schedule number" . "AAN")
    ("Consignment identifier, consignee assigned" . "AAO")
    ("Partial shipment identifier" . "AAP")
    ("Transport equipment identifier" . "AAQ")
    ("Municipality assigned business registry number" . "AAR")
    ("Transport contract document identifier" . "AAS")
    ("Master label number" . "AAT")
    ("Despatch note document identifier" . "AAU") ("Enquiry number" . "AAV")
    ("Docket number" . "AAW") ("Civil action number" . "AAX")
    ("Carrier's agent reference number" . "AAY")
    ("Standard Carrier Alpha Code (SCAC) number" . "AAZ")
    ("Customs valuation decision number" . "ABA")
    ("End use authorization number" . "ABB")
    ("Anti-dumping case number" . "ABC") ("Customs tariff number" . "ABD")
    ("Declarant's reference number" . "ABE") ("Repair estimate number" . "ABF")
    ("Customs decision request number" . "ABG")
    ("Sub-house bill of lading number" . "ABH")
    ("Tax payment identifier" . "ABI") ("Quota number" . "ABJ")
    ("Transit (onward carriage) guarantee (bond) number" . "ABK")
    ("Customs guarantee number" . "ABL") ("Replacing part number" . "ABM")
    ("Seller's catalogue number" . "ABN") ("Originator's reference" . "ABO")
    ("Declarant's Customs identity number" . "ABP")
    ("Importer reference number" . "ABQ")
    ("Export clearance instruction reference number" . "ABR")
    ("Import clearance instruction reference number" . "ABS")
    ("Goods declaration document identifier, Customs" . "ABT")
    ("Article number" . "ABU") ("Intra-plant routing" . "ABV")
    ("Stock keeping unit number" . "ABW")
    ("Text Element Identifier deletion reference" . "ABX")
    ("Allotment identification (Air)" . "ABY")
    ("Vehicle licence number" . "ABZ") ("Air cargo transfer manifest" . "AC")
    ("Cargo acceptance order reference number" . "ACA")
    ("US government agency number" . "ACB")
    ("Shipping unit identification" . "ACC")
    ("Additional reference number" . "ACD") ("Related document number" . "ACE")
    ("Addressee reference" . "ACF") ("ATA carnet number" . "ACG")
    ("Packaging unit identification" . "ACH")
    ("Outerpackaging unit identification" . "ACI")
    ("Customer material specification number" . "ACJ")
    ("Bank reference" . "ACK") ("Principal reference number" . "ACL")
    ("Collection advice document identifier" . "ACN")
    ("Iron charge number" . "ACO") ("Hot roll number" . "ACP")
    ("Cold roll number" . "ACQ") ("Railway wagon number" . "ACR")
    ("Unique claims reference number of the sender" . "ACT")
    ("Loss/event number" . "ACU") ("Estimate order reference number" . "ACV")
    ("Reference number to previous message" . "ACW")
    ("Banker's acceptance" . "ACX") ("Duty memo number" . "ACY")
    ("Equipment transport charge number" . "ACZ")
    ("Buyer's item number" . "ADA") ("Matured certificate of deposit" . "ADB")
    ("Loan" . "ADC") ("Analysis number/test number" . "ADD")
    ("Account number" . "ADE") ("Treaty number" . "ADF")
    ("Catastrophe number" . "ADG")
    ("Bureau signing (statement reference)" . "ADI")
    ("Company / syndicate reference 1" . "ADJ")
    ("Company / syndicate reference 2" . "ADK")
    ("Ordering customer consignment reference number" . "ADL")
    ("Shipowner's authorization number" . "ADM")
    ("Inland transport order number" . "ADN")
    ("Container work order reference number" . "ADO")
    ("Statement number" . "ADP") ("Unique market reference" . "ADQ")
    ("Group accounting" . "ADT") ("Broker reference 1" . "ADU")
    ("Broker reference 2" . "ADV") ("Lloyd's claims office reference" . "ADW")
    ("Secure delivery terms and conditions agreement reference" . "ADX")
    ("Report number" . "ADY") ("Trader account number" . "ADZ")
    ("Authorization for expense (AFE) number" . "AE")
    ("Government agency reference number" . "AEA") ("Assembly number" . "AEB")
    ("Symbol number" . "AEC") ("Commodity number" . "AED")
    ("Eur 1 certificate number" . "AEE")
    ("Customer process specification number" . "AEF")
    ("Customer specification number" . "AEG")
    ("Applicable instructions or standards" . "AEH")
    ("Registration number of previous Customs declaration" . "AEI")
    ("Post-entry reference" . "AEJ") ("Payment order number" . "AEK")
    ("Delivery number (transport)" . "AEL") ("Transport route" . "AEM")
    ("Customer's unit inventory number" . "AEN")
    ("Product reservation number" . "AEO") ("Project number" . "AEP")
    ("Drawing list number" . "AEQ") ("Project specification number" . "AER")
    ("Primary reference" . "AES") ("Request for cancellation number" . "AET")
    ("Supplier's control number" . "AEU") ("Shipping note number" . "AEV")
    ("Empty container bill number" . "AEW")
    ("Non-negotiable maritime transport document number" . "AEX")
    ("Substitute air waybill number" . "AEY")
    ("Despatch note (post parcels) number" . "AEZ")
    ("Airlines flight identification number" . "AF")
    ("Through bill of lading number" . "AFA") ("Cargo manifest number" . "AFB")
    ("Bordereau number" . "AFC") ("Customs item number" . "AFD")
    ("Export Control Commodity number (ECCN)" . "AFE")
    ("Marking/label reference" . "AFF") ("Tariff number" . "AFG")
    ("Replenishment purchase order number" . "AFH")
    ("Immediate transportation no. for in bond movement" . "AFI")
    ("Transportation exportation no. for in bond movement" . "AFJ")
    ("Immediate exportation no. for in bond movement" . "AFK")
    ("Associated invoices" . "AFL") ("Secondary Customs reference" . "AFM")
    ("Account party's reference" . "AFN") ("Beneficiary's reference" . "AFO")
    ("Second beneficiary's reference" . "AFP")
    ("Applicant's bank reference" . "AFQ") ("Issuing bank's reference" . "AFR")
    ("Beneficiary's bank reference" . "AFS")
    ("Direct payment valuation number" . "AFT")
    ("Direct payment valuation request number" . "AFU")
    ("Quantity valuation number" . "AFV")
    ("Quantity valuation request number" . "AFW")
    ("Bill of quantities number" . "AFX") ("Payment valuation number" . "AFY")
    ("Situation number" . "AFZ") ("Agreement to pay number" . "AGA")
    ("Contract party reference number" . "AGB")
    ("Account party's bank reference" . "AGC")
    ("Agent's bank reference" . "AGD") ("Agent's reference" . "AGE")
    ("Applicant's reference" . "AGF") ("Dispute number" . "AGG")
    ("Credit rating agency's reference number" . "AGH")
    ("Request number" . "AGI") ("Single transaction sequence number" . "AGJ")
    ("Application reference number" . "AGK")
    ("Delivery verification certificate" . "AGL")
    ("Number of temporary importation document" . "AGM")
    ("Reference number quoted on statement" . "AGN")
    ("Sender's reference to the original message" . "AGO")
    ("Company issued equipment ID" . "AGP") ("Domestic flight number" . "AGQ")
    ("International flight number" . "AGR")
    ("Employer identification number of service bureau" . "AGS")
    ("Service group identification number" . "AGT") ("Member number" . "AGU")
    ("Previous member number" . "AGV") ("Scheme/plan number" . "AGW")
    ("Previous scheme/plan number" . "AGX")
    ("Receiving party's member identification" . "AGY")
    ("Payroll number" . "AGZ") ("Packaging specification number" . "AHA")
    ("Authority issued equipment identification" . "AHB")
    ("Training flight number" . "AHC") ("Fund code number" . "AHD")
    ("Signal code number" . "AHE") ("Major force program number" . "AHF")
    ("Nomination number" . "AHG") ("Laboratory registration number" . "AHH")
    ("Transport contract reference number" . "AHI")
    ("Payee's reference number" . "AHJ") ("Payer's reference number" . "AHK")
    ("Creditor's reference number" . "AHL")
    ("Debtor's reference number" . "AHM")
    ("Joint venture reference number" . "AHN")
    ("Chamber of Commerce registration number" . "AHO")
    ("Tax registration number" . "AHP") ("Wool identification number" . "AHQ")
    ("Wool tax reference number" . "AHR")
    ("Meat processing establishment registration number" . "AHS")
    ("Quarantine/treatment status reference number" . "AHT")
    ("Request for quote number" . "AHU")
    ("Manual processing authority number" . "AHV") ("Rate note number" . "AHX")
    ("Freight Forwarder number" . "AHY") ("Customs release code" . "AHZ")
    ("Compliance code number" . "AIA")
    ("Department of transportation bond number" . "AIB")
    ("Export establishment number" . "AIC")
    ("Certificate of conformity" . "AID")
    ("Ministerial certificate of homologation" . "AIE")
    ("Previous delivery instruction number" . "AIF")
    ("Passport number" . "AIG") ("Common transaction reference number" . "AIH")
    ("Bank's common transaction reference number" . "AII")
    ("Customer's individual transaction reference number" . "AIJ")
    ("Bank's individual transaction reference number" . "AIK")
    ("Customer's common transaction reference number" . "AIL")
    ("Individual transaction reference number" . "AIM")
    ("Product sourcing agreement number" . "AIN")
    ("Customs transhipment number" . "AIO")
    ("Customs preference inquiry number" . "AIP")
    ("Packing plant number" . "AIQ") ("Original certificate number" . "AIR")
    ("Processing plant number" . "AIS") ("Slaughter plant number" . "AIT")
    ("Charge card account number" . "AIU") ("Event reference number" . "AIV")
    ("Transport section reference number" . "AIW")
    ("Referred product for mechanical analysis" . "AIX")
    ("Referred product for chemical analysis" . "AIY")
    ("Consolidated invoice number" . "AIZ")
    ("Part reference indicator in a drawing" . "AJA")
    ("U.S. Code of Federal Regulations (CFR)" . "AJB")
    ("Purchasing activity clause number" . "AJC")
    ("U.S. Defense Federal Acquisition Regulation Supplement" . "AJD")
    ("Agency clause number" . "AJE") ("Circular publication number" . "AJF")
    ("U.S. Federal Acquisition Regulation" . "AJG")
    ("U.S. General Services Administration Regulation" . "AJH")
    ("U.S. Federal Information Resources Management Regulation" . "AJI")
    ("Paragraph" . "AJJ") ("Special instructions number" . "AJK")
    ("Site specific procedures, terms, and conditions number" . "AJL")
    ("Master solicitation procedures, terms, and conditions" . "AJM")
    ("U.S. Department of Veterans Affairs Acquisition Regulation" . "AJN")
    ("Military Interdepartmental Purchase Request (MIPR) number" . "AJO")
    ("Foreign military sales number" . "AJP")
    ("Defense priorities allocation system priority rating" . "AJQ")
    ("Wage determination number" . "AJR") ("Agreement number" . "AJS")
    ("Standard Industry Classification (SIC) number" . "AJT")
    ("End item number" . "AJU") ("Federal supply schedule item number" . "AJV")
    ("Technical document number" . "AJW") ("Technical order number" . "AJX")
    ("Suffix" . "AJY") ("Transportation account number" . "AJZ")
    ("Container disposition order reference number" . "AKA")
    ("Container prefix" . "AKB")
    ("Transport equipment return reference" . "AKC")
    ("Transport equipment survey reference" . "AKD")
    ("Transport equipment survey report number" . "AKE")
    ("Transport equipment stuffing order" . "AKF")
    ("Vehicle Identification Number (VIN)" . "AKG")
    ("Government bill of lading" . "AKH")
    ("Ordering customer's second reference number" . "AKI")
    ("Direct debit reference" . "AKJ")
    ("Meter reading at the beginning of the delivery" . "AKK")
    ("Meter reading at the end of delivery" . "AKL")
    ("Replenishment purchase order range start number" . "AKM")
    ("Third bank's reference" . "AKN") ("Action authorization number" . "AKO")
    ("Appropriation number" . "AKP")
    ("Product change authority number" . "AKQ")
    ("General cargo consignment reference number" . "AKR")
    ("Catalogue sequence number" . "AKS") ("Forwarding order number" . "AKT")
    ("Transport equipment survey reference number" . "AKU")
    ("Lease contract reference" . "AKV")
    ("Transport costs reference number" . "AKW")
    ("Transport equipment stripping order" . "AKX")
    ("Prior policy number" . "AKY") ("Policy number" . "AKZ")
    ("Procurement budget number" . "ALA")
    ("Domestic inventory management code" . "ALB")
    ("Customer reference number assigned to previous balance of" . "ALC")
    ("Previous credit advice reference number" . "ALD")
    ("Reporting form number" . "ALE")
    ("Authorization number for exception to dangerous goods" . "ALF")
    ("Dangerous goods security number" . "ALG")
    ("Dangerous goods transport licence number" . "ALH")
    ("Previous rental agreement number" . "ALI")
    ("Next rental agreement reason number" . "ALJ")
    ("Consignee's invoice number" . "ALK") ("Message batch number" . "ALL")
    ("Previous delivery schedule number" . "ALM")
    ("Physical inventory recount reference number" . "ALN")
    ("Receiving advice number" . "ALO")
    ("Returnable container reference number" . "ALP")
    ("Returns notice number" . "ALQ") ("Sales forecast number" . "ALR")
    ("Sales report number" . "ALS") ("Previous tax control number" . "ALT")
    ("AGERD (Aerospace Ground Equipment Requirement Data) number" . "ALU")
    ("Registered capital reference" . "ALV")
    ("Standard number of inspection document" . "ALW") ("Model" . "ALX")
    ("Financial management reference" . "ALY")
    ("NOTIfication for COLlection number (NOTICOL)" . "ALZ")
    ("Previous request for metered reading reference number" . "AMA")
    ("Next rental agreement number" . "AMB")
    ("Reference number of a request for metered reading" . "AMC")
    ("Hastening number" . "AMD") ("Repair data request number" . "AME")
    ("Consumption data request number" . "AMF") ("Profile number" . "AMG")
    ("Case number" . "AMH")
    ("Government quality assurance and control level Number" . "AMI")
    ("Payment plan reference" . "AMJ") ("Replaced meter unit number" . "AMK")
    ("Replenishment purchase order range end number" . "AML")
    ("Insurer assigned reference number" . "AMM")
    ("Canadian excise entry number" . "AMN") ("Premium rate table" . "AMO")
    ("Advise through bank's reference" . "AMP")
    ("US, Department of Transportation bond surety code" . "AMQ")
    ("US, Food and Drug Administration establishment indicator" . "AMR")
    ("US, Federal Communications Commission (FCC) import" . "AMS")
    ("Goods and Services Tax identification number" . "AMT")
    ("Integrated logistic support cross reference number" . "AMU")
    ("Department number" . "AMV") ("Buyer's catalogue number" . "AMW")
    ("Financial settlement party's reference number" . "AMX")
    ("Standard's version number" . "AMY") ("Pipeline number" . "AMZ")
    ("Account servicing bank's reference number" . "ANA")
    ("Completed units payment request reference" . "ANB")
    ("Payment in advance request reference" . "ANC") ("Parent file" . "AND")
    ("Sub file" . "ANE") ("CAD file layer convention" . "ANF")
    ("Technical regulation" . "ANG") ("Plot file" . "ANH")
    ("File conversion journal" . "ANI") ("Authorization number" . "ANJ")
    ("Reference number assigned by third party" . "ANK")
    ("Deposit reference number" . "ANL") ("Named bank's reference" . "ANM")
    ("Drawee's reference" . "ANN") ("Case of need party's reference" . "ANO")
    ("Collecting bank's reference" . "ANP")
    ("Remitting bank's reference" . "ANQ")
    ("Principal's bank reference" . "ANR")
    ("Presenting bank's reference" . "ANS") ("Consignee's reference" . "ANT")
    ("Financial transaction reference number" . "ANU")
    ("Credit reference number" . "ANV")
    ("Receiving bank's authorization number" . "ANW")
    ("Clearing reference" . "ANX") ("Sending bank's reference number" . "ANY")
    ("Documentary payment reference" . "AOA")
    ("Accounting file reference" . "AOD")
    ("Sender's file reference number" . "AOE")
    ("Receiver's file reference number" . "AOF")
    ("Source document internal reference" . "AOG")
    ("Principal's reference" . "AOH") ("Debit reference number" . "AOI")
    ("Calendar" . "AOJ") ("Work shift" . "AOK")
    ("Work breakdown structure" . "AOL")
    ("Organisation breakdown structure" . "AOM")
    ("Work task charge number" . "AON") ("Functional work group" . "AOO")
    ("Work team" . "AOP") ("Department" . "AOQ") ("Statement of work" . "AOR")
    ("Work package" . "AOS") ("Planning package" . "AOT")
    ("Cost account" . "AOU") ("Work order" . "AOV")
    ("Transportation Control Number (TCN)" . "AOW")
    ("Constraint notation" . "AOX") ("ETERMS reference" . "AOY")
    ("Implementation version number" . "AOZ")
    ("Accounts receivable number" . "AP")
    ("Incorporated legal reference" . "APA")
    ("Payment instalment reference number" . "APB")
    ("Equipment owner reference number" . "APC")
    ("Cedent's claim number" . "APD") ("Reinsurer's claim number" . "APE")
    ("Price/sales catalogue response reference number" . "APF")
    ("General purpose message reference number" . "APG")
    ("Invoicing data sheet reference number" . "APH")
    ("Inventory report reference number" . "API")
    ("Ceiling formula reference number" . "APJ")
    ("Price variation formula reference number" . "APK")
    ("Reference to account servicing bank's message" . "APL")
    ("Party sequence number" . "APM") ("Purchaser's request reference" . "APN")
    ("Contractor request reference" . "APO")
    ("Accident reference number" . "APP")
    ("Commercial account summary reference number" . "APQ")
    ("Contract breakdown reference" . "APR")
    ("Contractor registration number" . "APS")
    ("Applicable coefficient identification number" . "APT")
    ("Special budget account number" . "APU")
    ("Authorisation for repair reference" . "APV")
    ("Manufacturer defined repair rates reference" . "APW")
    ("Original submitter log number" . "APX")
    ("Original submitter, parent Data Maintenance Request (DMR)" . "APY")
    ("Original submitter, child Data Maintenance Request (DMR)" . "APZ")
    ("Entry point assessment log number" . "AQA")
    ("Entry point assessment log number, parent DMR" . "AQB")
    ("Entry point assessment log number, child DMR" . "AQC")
    ("Data structure tag" . "AQD") ("Central secretariat log number" . "AQE")
    ("Central secretariat log number, parent Data Maintenance" . "AQF")
    ("Central secretariat log number, child Data Maintenance" . "AQG")
    ("International assessment log number" . "AQH")
    ("International assessment log number, parent Data" . "AQI")
    ("International assessment log number, child Data Maintenance" . "AQJ")
    ("Status report number" . "AQK") ("Message design group number" . "AQL")
    ("US Customs Service (USCS) entry code" . "AQM")
    ("Beginning job sequence number" . "AQN")
    ("Sender's clause number" . "AQO")
    ("Dun and Bradstreet Canada's 8 digit Standard Industrial" . "AQP")
    ("Activite Principale Exercee (APE) identifier" . "AQQ")
    ("Dun and Bradstreet US 8 digit Standard Industrial" . "AQR")
    ("Nomenclature Activity Classification Economy (NACE)" . "AQS")
    ("Norme Activite Francaise (NAF) identifier" . "AQT")
    ("Registered contractor activity type" . "AQU")
    ("Statistic Bundes Amt (SBA) identifier" . "AQV")
    ("State or province assigned entity identification" . "AQW")
    ("Institute of Security and Future Market Development (ISFMD)" . "AQX")
    ("File identification number" . "AQY")
    ("Bankruptcy procedure number" . "AQZ")
    ("National government business identification number" . "ARA")
    ("Prior Data Universal Number System (DUNS) number" . "ARB")
    ("Companies Registry Office (CRO) number" . "ARC")
    ("Costa Rican judicial number" . "ARD")
    ("Numero de Identificacion Tributaria (NIT)" . "ARE")
    ("Patron number" . "ARF")
    ("Registro Informacion Fiscal (RIF) number" . "ARG")
    ("Registro Unico de Contribuyente (RUC) number" . "ARH")
    ("Tokyo SHOKO Research (TSR) business identifier" . "ARI")
    ("Personal identity card number" . "ARJ")
    ("Systeme Informatique pour le Repertoire des ENtreprises" . "ARK")
    ("Systeme Informatique pour le Repertoire des ETablissements" . "ARL")
    ("Publication issue number" . "ARM") ("Original filing number" . "ARN")
    ("Document page identifier" . "ARO")
    ("Public filing registration number" . "ARP")
    ("Regiristo Federal de Contribuyentes" . "ARQ")
    ("Social security number" . "ARR") ("Document volume number" . "ARS")
    ("Book number" . "ART") ("Stock exchange company identifier" . "ARU")
    ("Imputation account" . "ARV") ("Financial phase reference" . "ARW")
    ("Technical phase reference" . "ARX")
    ("Prior contractor registration number" . "ARY")
    ("Stock adjustment number" . "ARZ") ("Dispensation reference" . "ASA")
    ("Investment reference number" . "ASB") ("Assuming company" . "ASC")
    ("Budget chapter" . "ASD") ("Duty free products security number" . "ASE")
    ("Duty free products receipt authorisation number" . "ASF")
    ("Party information message reference" . "ASG")
    ("Formal statement reference" . "ASH")
    ("Proof of delivery reference number" . "ASI")
    ("Supplier's credit claim reference number" . "ASJ")
    ("Picture of actual product" . "ASK")
    ("Picture of a generic product" . "ASL")
    ("Trading partner identification number" . "ASM")
    ("Prior trading partner identification number" . "ASN")
    ("Password" . "ASO") ("Formal report number" . "ASP")
    ("Fund account number" . "ASQ") ("Safe custody number" . "ASR")
    ("Master account number" . "ASS") ("Group reference number" . "AST")
    ("Accounting transmission number" . "ASU")
    ("Product data file number" . "ASV")
    ("Cadastro Geral do Contribuinte (CGC)" . "ASW")
    ("Foreign resident identification number" . "ASX") ("CD-ROM" . "ASY")
    ("Physical medium" . "ASZ")
    ("Financial cancellation reference number" . "ATA")
    ("Purchase for export Customs agreement number" . "ATB")
    ("Judgment number" . "ATC") ("Secretariat number" . "ATD")
    ("Previous banking status message reference" . "ATE")
    ("Last received banking status message reference" . "ATF")
    ("Bank's documentary procedure reference" . "ATG")
    ("Customer's documentary procedure reference" . "ATH")
    ("Safe deposit box number" . "ATI") ("Receiving Bankgiro number" . "ATJ")
    ("Sending Bankgiro number" . "ATK") ("Bankgiro reference" . "ATL")
    ("Guarantee number" . "ATM") ("Collection instrument number" . "ATN")
    ("Converted Postgiro number" . "ATO")
    ("Cost centre alignment number" . "ATP")
    ("Kamer Van Koophandel (KVK) number" . "ATQ")
    ("Institut Belgo-Luxembourgeois de Codification (IBLC) number" . "ATR")
    ("External object reference" . "ATS")
    ("Exceptional transport authorisation number" . "ATT")
    ("Clave Unica de Identificacion Tributaria (CUIT)" . "ATU")
    ("Registro Unico Tributario (RUT)" . "ATV")
    ("Flat rack container bundle identification number" . "ATW")
    ("Transport equipment acceptance order reference" . "ATX")
    ("Transport equipment release order reference" . "ATY")
    ("Ship's stay reference number" . "ATZ")
    ("Authorization to meet competition number" . "AU")
    ("Place of positioning reference" . "AUA") ("Party reference" . "AUB")
    ("Issued prescription identification" . "AUC")
    ("Collection reference" . "AUD") ("Travel service" . "AUE")
    ("Consignment stock contract" . "AUF")
    ("Importer's letter of credit reference" . "AUG")
    ("Performed prescription identification" . "AUH")
    ("Image reference" . "AUI")
    ("Proposed purchase order reference number" . "AUJ")
    ("Application for financial support reference number" . "AUK")
    ("Manufacturing quality agreement number" . "AUL")
    ("Software editor reference" . "AUM") ("Software reference" . "AUN")
    ("Software quality reference" . "AUO")
    ("Consolidated orders' reference" . "AUP")
    ("Customs binding ruling number" . "AUQ")
    ("Customs non-binding ruling number" . "AUR")
    ("Delivery route reference" . "AUS")
    ("Net area supplier reference" . "AUT") ("Time series reference" . "AUU")
    ("Connecting point to central grid" . "AUV")
    ("Marketing plan identification number (MPIN)" . "AUW")
    ("Entity reference number, previous" . "AUX")
    ("International Standard Industrial Classification (ISIC)" . "AUY")
    ("Customs pre-approval ruling number" . "AUZ")
    ("Account payable number" . "AV")
    ("First financial institution's transaction reference" . "AVA")
    ("Product characteristics directory" . "AVB")
    ("Supplier's customer reference number" . "AVC")
    ("Inventory report request number" . "AVD") ("Metering point" . "AVE")
    ("Passenger reservation number" . "AVF")
    ("Slaughterhouse approval number" . "AVG")
    ("Meat cutting plant approval number" . "AVH")
    ("Customer travel service identifier" . "AVI")
    ("Export control classification number" . "AVJ")
    ("Broker reference 3" . "AVK") ("Consignment information" . "AVL")
    ("Goods item information" . "AVM") ("Dangerous Goods information" . "AVN")
    ("Pilotage services exemption number" . "AVO")
    ("Person registration number" . "AVP")
    ("Place of packing approval number" . "AVQ")
    ("Original Mandate Reference" . "AVR") ("Mandate Reference" . "AVS")
    ("Reservation station indentifier" . "AVT")
    ("Unique goods shipment identifier" . "AVU")
    ("Framework Agreement Number" . "AVV") ("Hash value" . "AVW")
    ("Movement reference number" . "AVX")
    ("Economic Operators Registration and Identification Number" . "AVY")
    ("Local Reference Number" . "AVZ") ("Rate code number" . "AWA")
    ("Air waybill number" . "AWB")
    ("Documentary credit amendment number" . "AWC")
    ("Advising bank's reference" . "AWD") ("Cost centre" . "AWE")
    ("Work item quantity determination" . "AWF")
    ("Internal data process number" . "AWG")
    ("Category of work reference" . "AWH") ("Policy form number" . "AWI")
    ("Net area" . "AWJ") ("Service provider" . "AWK")
    ("Error position" . "AWL") ("Service category reference" . "AWM")
    ("Connected location" . "AWN") ("Related party" . "AWO")
    ("Latest accounting entry record reference" . "AWP")
    ("Accounting entry" . "AWQ") ("Document reference, original" . "AWR")
    ("Hygienic Certificate number, national" . "AWS")
    ("Administrative Reference Code" . "AWT") ("Pick-up sheet number" . "AWU")
    ("Phone number" . "AWV") ("Buyer's fund number" . "AWW")
    ("Company trading account number" . "AWX")
    ("Reserved goods identifier" . "AWY")
    ("Handling and movement reference number" . "AWZ")
    ("Instruction to despatch reference number" . "AXA")
    ("Instruction for returns number" . "AXB")
    ("Metered services consumption report number" . "AXC")
    ("Order status enquiry number" . "AXD")
    ("Firm booking reference number" . "AXE")
    ("Product inquiry number" . "AXF") ("Split delivery number" . "AXG")
    ("Service relation number" . "AXH")
    ("Serial shipping container code" . "AXI")
    ("Test specification number" . "AXJ")
    ("Transport status report number" . "AXK")
    ("Tooling contract number" . "AXL") ("Formula reference number" . "AXM")
    ("Pre-agreement number" . "AXN") ("Product certification number" . "AXO")
    ("Consignment contract number" . "AXP")
    ("Product specification reference number" . "AXQ")
    ("Payroll deduction advice reference" . "AXR")
    ("TRACES party identification" . "AXS")
    ("Beginning meter reading actual" . "BA")
    ("Buyer's contract number" . "BC") ("Bid number" . "BD")
    ("Beginning meter reading estimated" . "BE")
    ("House bill of lading number" . "BH") ("Bill of lading number" . "BM")
    ("Consignment identifier, carrier assigned" . "BN")
    ("Blanket order number" . "BO") ("Broker or sales office number" . "BR")
    ("Batch number/lot number" . "BT")
    ("Battery and accumulator producer registration number" . "BTP")
    ("Blended with number" . "BW")
    ("IATA Cargo Agent CASS Address number" . "CAS")
    ("Matching of entries, balanced" . "CAT") ("Entry flagging" . "CAU")
    ("Matching of entries, unbalanced" . "CAV")
    ("Document reference, internal" . "CAW")
    ("European Value Added Tax identification" . "CAX")
    ("Cost accounting document" . "CAY")
    ("Grid operator's customer reference number" . "CAZ")
    ("Ticket control number" . "CBA")
    ("Order shipment grouping reference" . "CBB") ("Credit note number" . "CD")
    ("Ceding company" . "CEC") ("Debit letter number" . "CED")
    ("Consignee's further order" . "CFE")
    ("Animal farm licence number" . "CFF")
    ("Consignor's further order" . "CFO") ("Consignee's order number" . "CG")
    ("Customer catalogue number" . "CH") ("Cheque number" . "CK")
    ("Checking number" . "CKN") ("Credit memo number" . "CM")
    ("Road consignment note number" . "CMR")
    ("Carrier's reference number" . "CN")
    ("Charges note document attachment indicator" . "CNO")
    ("Call off order number" . "COF")
    ("Condition of purchase document number" . "CP")
    ("Customer reference number" . "CR")
    ("Transport means journey identifier" . "CRN")
    ("Condition of sale document number" . "CS")
    ("Team assignment number" . "CST") ("Contract number" . "CT")
    ("Consignment identifier, consignor assigned" . "CU")
    ("Container operators reference number" . "CV") ("Package number" . "CW")
    ("Cooperation contract number" . "CZ") ("Deferment approval number" . "DA")
    ("Debit account number" . "DAN") ("Buyer's debtor number" . "DB")
    ("Distributor invoice number" . "DI") ("Debit note number" . "DL")
    ("Document identifier" . "DM") ("Delivery note number" . "DQ")
    ("Dock receipt number" . "DR") ("Ending meter reading actual" . "EA")
    ("Embargo permit number" . "EB") ("Export declaration" . "ED")
    ("Ending meter reading estimated" . "EE")
    ("Electrical and electronic equipment producer registration" . "EEP")
    ("Employer's identification number" . "EI") ("Embargo number" . "EN")
    ("Equipment number" . "EQ") ("Container/equipment receipt number" . "ER")
    ("Exporter's reference number" . "ERN")
    ("Excess transportation number" . "ET") ("Export permit identifier" . "EX")
    ("Fiscal number" . "FC")
    ("Consignment identifier, freight forwarder assigned" . "FF")
    ("File line identifier" . "FI") ("Flow reference number" . "FLW")
    ("Freight bill number" . "FN") ("Foreign exchange" . "FO")
    ("Final sequence number" . "FS") ("Free zone identifier" . "FT")
    ("File version number" . "FV") ("Foreign exchange contract number" . "FX")
    ("Standard's number" . "GA") ("Government contract number" . "GC")
    ("Standard's code number" . "GD") ("General declaration number" . "GDN")
    ("Government reference number" . "GN") ("Harmonised system number" . "HS")
    ("House waybill number" . "HWB") ("Internal vendor number" . "IA")
    ("In bond number" . "IB") ("IATA cargo agent code number" . "ICA")
    ("Insurance certificate reference number" . "ICE")
    ("Insurance contract reference number" . "ICO")
    ("Initial sample inspection report number" . "II")
    ("Internal order number" . "IL") ("Intermediary broker" . "INB")
    ("Interchange number new" . "INN") ("Interchange number old" . "INO")
    ("Import permit identifier" . "IP") ("Invoice number suffix" . "IS")
    ("Internal customer number" . "IT") ("Invoice document identifier" . "IV")
    ("Job number" . "JB") ("Ending job sequence number" . "JE")
    ("Shipping label serial number" . "LA")
    ("Loading authorisation identifier" . "LAN")
    ("Lower number in range" . "LAR") ("Lockbox" . "LB")
    ("Letter of credit number" . "LC") ("Document line identifier" . "LI")
    ("Load planning number" . "LO") ("Reservation office identifier" . "LRC")
    ("Bar coded label serial number" . "LS")
    ("Ship notice/manifest number" . "MA")
    ("Master bill of lading number" . "MB")
    ("Manufacturer's part number" . "MF") ("Meter unit number" . "MG")
    ("Manufacturing order number" . "MH") ("Message recipient" . "MR")
    ("Mailing reference number" . "MRN") ("Message sender" . "MS")
    ("Manufacturer's material safety data sheet number" . "MSS")
    ("Master air waybill number" . "MWB")
    ("North American hazardous goods classification number" . "NA")
    ("Nota Fiscal" . "NF") ("Current invoice number" . "OH")
    ("Previous invoice number" . "OI")
    ("Order document identifier, buyer assigned" . "ON")
    ("Original purchase order" . "OP") ("General order number" . "OR")
    ("Payer's financial institution account number" . "PB")
    ("Production code" . "PC") ("Promotion deal number" . "PD")
    ("Plant number" . "PE") ("Prime contractor contract number" . "PF")
    ("Price list version number" . "PI") ("Packing list number" . "PK")
    ("Price list number" . "PL") ("Purchase order response number" . "POR")
    ("Purchase order change number" . "PP") ("Payment reference" . "PQ")
    ("Price quote number" . "PR") ("Purchase order number suffix" . "PS")
    ("Prior purchase order number" . "PW")
    ("Payee's financial institution account number" . "PY")
    ("Remittance advice number" . "RA") ("Rail/road routing code" . "RC")
    ("Railway consignment note number" . "RCN") ("Release number" . "RE")
    ("Consignment receipt identifier" . "REN")
    ("Export reference number" . "RF")
    ("Payer's financial institution transit routing No.(ACH transfers)" . "RR")
    ("Payee's financial institution transit routing No." . "RT")
    ("Sales person number" . "SA") ("Sales region number" . "SB")
    ("Sales department number" . "SD") ("Serial number" . "SE")
    ("Allocated seat" . "SEA") ("Ship from" . "SF")
    ("Previous highest schedule number" . "SH")
    ("SID (Shipper's identifying number for shipment)" . "SI")
    ("Sales office number" . "SM")
    ("Transport equipment seal identifier" . "SN") ("Scan line" . "SP")
    ("Equipment sequence number" . "SQ") ("Shipment reference number" . "SRN")
    ("Sellers reference number" . "SS") ("Station reference number" . "STA")
    ("Swap order number" . "SW") ("Specification number" . "SZ")
    ("Trucker's bill of lading" . "TB")
    ("Terminal operator's consignment reference" . "TCR")
    ("Telex message number" . "TE") ("Transfer number" . "TF")
    ("TIR carnet number" . "TI") ("Transport instruction number" . "TIN")
    ("Tax exemption licence number" . "TL")
    ("Transaction reference number" . "TN") ("Test report number" . "TP")
    ("Upper number of range" . "UAR")
    ("Ultimate customer's reference number" . "UC")
    ("Unique consignment reference number" . "UCN")
    ("United Nations Dangerous Goods identifier" . "UN")
    ("Ultimate customer's order number" . "UO")
    ("Uniform Resource Identifier" . "URI") ("VAT registration number" . "VA")
    ("Vendor contract number" . "VC")
    ("Transport equipment gross mass verification reference" . "VGR")
    ("Vessel identifier" . "VM") ("Order number (vendor)" . "VN")
    ("Voyage number" . "VON")
    ("Transport equipment gross mass verification order reference" . "VOR")
    ("Vendor product number" . "VP") ("Vendor ID number" . "VR")
    ("Vendor order number suffix" . "VS")
    ("Motor vehicle identification number" . "VT") ("Voucher number" . "VV")
    ("Warehouse entry number" . "WE") ("Weight agreement number" . "WM")
    ("Well number" . "WN") ("Warehouse receipt number" . "WR")
    ("Warehouse storage location number" . "WS") ("Rail waybill number" . "WY")
    ("Company/place registration number" . "XA")
    ("Cargo control number" . "XC") ("Previous cargo control number" . "XP")
    ("Mutually defined reference number" . "ZZZ")))

(EXPORT '|Invoiced object identifier scheme (UNCL 1153)| :PEPPOL/CODE-LISTS)