(IN-PACKAGE :PEPPOL/CODE-LISTS)

(DEFVAR |ISO 6523 ICD list|
  '(("System Information et Repertoire des Entreprise et des Etablissements: SIRENE"
     . "0002")
    ("Codification Numerique des Etablissments Financiers En Belgique"
     . "0003")
    ("NBS/OSI NETWORK" . "0004") ("USA FED GOV OSI NETWORK" . "0005")
    ("USA DOD OSI NETWORK" . "0006") ("Organisationsnummer" . "0007")
    ("LE NUMERO NATIONAL" . "0008") ("SIRET-CODE" . "0009")
    ("Organizational Identifiers for Structured Names under ISO 9541 Part 2"
     . "0010")
    ("International Code Designator for the Identification of OSI-based, Amateur Radio
            Organizations, Network Objects and Application Services."
     . "0011")
    ("European Computer Manufacturers Association: ECMA" . "0012")
    ("VSA FTP CODE (FTP = File Transfer Protocol)" . "0013")
    ("NIST/OSI Implememts' Workshop" . "0014")
    ("Electronic Data Interchange: EDI" . "0015")
    ("EWOS Object Identifiers" . "0016") ("COMMON LANGUAGE" . "0017")
    ("SNA/OSI Network" . "0018")
    ("Air Transport Industry Services Communications Network" . "0019")
    ("European Laboratory for Particle Physics: CERN" . "0020")
    ("SOCIETY FOR WORLDWIDE INTERBANK FINANCIAL, TELECOMMUNICATION S.W.I.F.T."
     . "0021")
    ("OSF Distributed Computing Object Identification" . "0022")
    ("Nordic University and Research Network: NORDUnet" . "0023")
    ("Digital Equipment Corporation: DEC" . "0024")
    ("OSI ASIA-OCEANIA WORKSHOP" . "0025")
    ("NATO ISO 6523 ICDE coding scheme" . "0026")
    ("Aeronautical Telecommunications Network (ATN)" . "0027")
    ("International Standard ISO 6523" . "0028")
    ("The All-Union Classifier of Enterprises and Organisations" . "0029")
    ("AT&T/OSI Network" . "0030") ("EDI Partner Identification Code" . "0031")
    ("Telecom Australia" . "0032") ("S G W OSI Internetwork" . "0033")
    ("Reuter Open Address Standard" . "0034") ("ISO 6523 - ICD" . "0035")
    ("TeleTrust Object Identifiers" . "0036") ("LY-tunnus" . "0037")
    ("The Australian GOSIP Network" . "0038")
    ("The OZ DOD OSI Network" . "0039") ("Unilever Group Companies" . "0040")
    ("Citicorp Global Information Network" . "0041")
    ("DBP Telekom Object Identifiers" . "0042") ("HydroNETT" . "0043")
    ("Thai Industrial Standards Institute (TISI)" . "0044")
    ("ICI Company Identification System" . "0045") ("FUNLOC" . "0046")
    ("BULL ODI/DSA/UNIX Network" . "0047") ("OSINZ" . "0048")
    ("Auckland Area Health" . "0049") ("Firmenich" . "0050")
    ("AGFA-DIS" . "0051")
    ("Society of Motion Picture and Television Engineers (SMPTE)" . "0052")
    ("Migros_Network M_NETOPZ" . "0053") ("ISO6523 - ICDPCR" . "0054")
    ("Energy Net" . "0055") ("Nokia Object Identifiers (NOI)" . "0056")
    ("Saint Gobain" . "0057") ("Siemens Corporate Network" . "0058")
    ("DANZNET" . "0059")
    ("Data Universal Numbering System (D-U-N-S Number)" . "0060")
    ("SOFFEX OSI" . "0061") ("KPN OVN" . "0062") ("ascomOSINet" . "0063")
    ("UTC: Uniforme Transport Code" . "0064") ("SOLVAY OSI CODING" . "0065")
    ("Roche Corporate Network" . "0066") ("ZellwegerOSINet" . "0067")
    ("Intel Corporation OSI" . "0068") ("SITA Object Identifier Tree" . "0069")
    ("DaimlerChrysler Corporate Network" . "0070")
    ("LEGO /OSI NETWORK" . "0071") ("NAVISTAR/OSI Network" . "0072")
    ("ICD Formatted ATM address" . "0073") ("ARINC" . "0074")
    ("Alcanet/Alcatel-Alsthom Corporate Network" . "0075")
    ("Sistema Italiano di Identificazione di ogetti gestito da UNINFO"
     . "0076")
    ("Sistema Italiano di Indirizzamento di Reti OSI Gestito da UNINFO"
     . "0077")
    ("Mitel terminal or switching equipment" . "0078") ("ATM Forum" . "0079")
    ("UK National Health Service Scheme, (EDIRA compliant)" . "0080")
    ("International NSAP" . "0081")
    ("Norwegian Telecommunications Authority's, NTA'S, EDI, identifier scheme (EDIRA
            compliant)"
     . "0082")
    ("Advanced Telecommunications Modules Limited, Corporate Network" . "0083")
    ("Athens Chamber of Commerce & Industry Scheme (EDIRA compliant)" . "0084")
    ("Swiss Chambers of Commerce Scheme (EDIRA) compliant" . "0085")
    ("United States Council for International Business (USCIB) Scheme, (EDIRA
            compliant)"
     . "0086")
    ("National Federation of Chambers of Commerce & Industry of Belgium, Scheme (EDIRA
            compliant)"
     . "0087")
    ("EAN Location Code" . "0088")
    ("The Association of British Chambers of Commerce Ltd. Scheme, (EDIRA compliant)"
     . "0089")
    ("Internet IP addressing - ISO 6523 ICD encoding" . "0090")
    ("Cisco Sysytems / OSI Network" . "0091")
    ("Revenue Canada Business Number Registration (EDIRA compliant)" . "0093")
    ("DEUTSCHER INDUSTRIE- UND HANDELSTAG (DIHT) Scheme (EDIRA compliant)"
     . "0094")
    ("Hewlett - Packard Company Internal AM Network" . "0095")
    ("DANISH CHAMBER OF COMMERCE Scheme (EDIRA compliant)" . "0096")
    ("FTI - Ediforum Italia, (EDIRA compliant)" . "0097")
    ("CHAMBER OF COMMERCE TEL AVIV-JAFFA Scheme (EDIRA compliant)" . "0098")
    ("Siemens Supervisory Systems Network" . "0099")
    ("PNG_ICD Scheme" . "0100") ("South African Code Allocation" . "0101")
    ("HEAG" . "0102") ("BT - ICD Coding System" . "0104")
    ("Portuguese Chamber of Commerce and Industry Scheme (EDIRA compliant)"
     . "0105")
    ("Vereniging van Kamers van Koophandel en Fabrieken in Nederland (Association of
            Chambers of Commerce and Industry in the Netherlands), Scheme (EDIRA compliant)"
     . "0106")
    ("Association of Swedish Chambers of Commerce and Industry Scheme (EDIRA
            compliant)"
     . "0107")
    ("Australian Chambers of Commerce and Industry Scheme (EDIRA compliant)"
     . "0108")
    ("BellSouth ICD AESA (ATM End System Address)" . "0109")
    ("Bell Atlantic" . "0110") ("Object Identifiers" . "0111")
    ("ISO register for Standards producing Organizations" . "0112")
    ("OriginNet" . "0113") ("Check Point Software Technologies" . "0114")
    ("Pacific Bell Data Communications Network" . "0115")
    ("PSS Object Identifiers" . "0116") ("STENTOR-ICD CODING SYSTEM" . "0117")
    ("ATM-Network ZN'96" . "0118") ("MCI / OSI Network" . "0119")
    ("Advantis" . "0120") ("Affable Software Data Interchange Codes" . "0121")
    ("BB-DATA GmbH" . "0122") ("BASF Company ATM-Network" . "0123")
    ("IOTA Identifiers for Organizations for Telecommunications Addressing using the ICD
            system format defined in ISO/IEC 8348"
     . "0124")
    ("Henkel Corporate Network (H-Net)" . "0125") ("GTE/OSI Network" . "0126")
    ("Dresdner Bank Corporate Network" . "0127")
    ("BCNR (Swiss Clearing Bank Number)" . "0128")
    ("BPI (Swiss Business Partner Identification) code" . "0129")
    ("Directorates of the European Commission" . "0130")
    ("Code for the Identification of National Organizations" . "0131")
    ("Certicom Object Identifiers" . "0132") ("TC68 OID" . "0133")
    ("Infonet Services Corporation" . "0134")
    ("SIA Object Identifiers" . "0135")
    ("Cable & Wireless Global ATM End-System Address Plan" . "0136")
    ("Global AESA scheme" . "0137")
    ("France Telecom ATM End System Address Plan" . "0138")
    ("Savvis Communications AESA:." . "0139")
    ("Toshiba Organizations, Partners, And Suppliers' (TOPAS) Code" . "0140")
    ("NATO Commercial and Government Entity system" . "0141")
    ("SECETI Object Identifiers" . "0142") ("EINESTEINet AG" . "0143")
    ("DoDAAC (Department of Defense Activity Address Code)" . "0144")
    ("DGCP (Direction Générale de la Comptabilité Publique)administrative accounting
            identification scheme"
     . "0145")
    ("DGI (Direction Générale des Impots) code" . "0146")
    ("Standard Company Code" . "0147")
    ("ITU (International Telecommunications Union)Data Network Identification Codes
            (DNIC)"
     . "0148")
    ("Global Business Identifier" . "0149")
    ("Madge Networks Ltd- ICD ATM Addressing Scheme" . "0150")
    ("Australian Business Number (ABN) Scheme" . "0151")
    ("Edira Scheme Identifier Code" . "0152")
    ("Concert Global Network Services ICD AESA" . "0153")
    ("Identification number of economic subjects: (ICO)" . "0154")
    ("Global Crossing AESA (ATM End System Address)" . "0155")
    ("AUNA" . "0156")
    ("ATM interconnection with the Dutch KPN Telecom" . "0157")
    ("Identification number of economic subject (ICO) Act on State Statistics of 29 November
            2001, § 27"
     . "0158")
    ("ACTALIS Object Identifiers" . "0159")
    ("GTIN - Global Trade Item Number" . "0160")
    ("ECCMA Open Technical Directory" . "0161")
    ("CEN/ISSS Object Identifier Scheme" . "0162")
    ("US-EPA Facility Identifier" . "0163") ("TELUS Corporation" . "0164")
    ("FIEIE Object identifiers" . "0165")
    ("Swissguide Identifier Scheme" . "0166")
    ("Priority Telecom ATM End System Address Plan" . "0167")
    ("Vodafone Ireland OSI Addressing" . "0168")
    ("Swiss Federal Business Identification Number. Central Business names Index (zefix)
            Identification Number"
     . "0169")
    ("Teikoku Company Code" . "0170")
    ("Luxembourg CP & CPS (Certification Policy and Certification Practice Statement)
            Index"
     . "0171")
    ("Project Group “Lists of Properties” (PROLIST®)" . "0172")
    ("eCI@ss" . "0173") ("StepNexus" . "0174") ("Siemens AG" . "0175")
    ("Paradine GmbH" . "0176") ("Odette International Limited" . "0177")
    ("Route1 MobiNET" . "0178") ("Penango Object Identifiers" . "0179")
    ("Lithuanian military PKI" . "0180")
    ("Numéro d'identification suisse des enterprises (IDE), Swiss Unique Business
            Identification Number (UIDB)"
     . "0183")
    ("DIGSTORG" . "0184") ("Perceval Object Code" . "0185")
    ("TrustPoint Object Identifiers" . "0186")
    ("Amazon Unique Identification Scheme" . "0187")
    ("Corporate Number of The Social Security and Tax Number System" . "0188")
    ("European Business Identifier (EBID)" . "0189")
    ("Organisatie Indentificatie Nummer (OIN)" . "0190")
    ("Company Code (Estonia)" . "0191") ("Organisasjonsnummer" . "0192")
    ("UBL.BE Party Identifier" . "0193")
    ("KOIOS Open Technical Dictionary" . "0194")
    ("Singapore Nationwide E-lnvoice Framework" . "0195")
    ("Icelandic identifier - Íslensk kennitala" . "0196")
    ("Name not known" . "0197") ("ERSTORG" . "0198")
    ("Legal Entity Identifier (LEI)" . "0199")
    ("Legal entity code (Lithuania)" . "0200")
    ("Codice Univoco Unità Organizzativa iPA" . "0201")
    ("Indirizzo di Posta Elettronica Certificata" . "0202")
    ("eDelivery Network Participant identifier" . "0203")
    ("Leitweg-ID" . "0204") ("Name not known" . "0205")
    ("Name not known" . "0206") ("Name not known" . "0207")
    ("Numero d'entreprise / ondernemingsnummer / Unternehmensnummer" . "0208")))

(EXPORT '|ISO 6523 ICD list| :PEPPOL/CODE-LISTS)