(IN-PACKAGE :PEPPOL/CODE-LISTS)

(DEFVAR |Payment means code (UNCL4461)|
  '(("Instrument not defined" . "1") ("Automated clearing house credit" . "2")
    ("Automated clearing house debit" . "3")
    ("ACH demand debit reversal" . "4") ("ACH demand credit reversal" . "5")
    ("ACH demand credit" . "6") ("ACH demand debit" . "7") ("Hold" . "8")
    ("National or regional clearing" . "9") ("In cash" . "10")
    ("ACH savings credit reversal" . "11")
    ("ACH savings debit reversal" . "12") ("ACH savings credit" . "13")
    ("ACH savings debit" . "14") ("Bookentry credit" . "15")
    ("Bookentry debit" . "16")
    ("ACH demand cash concentration/disbursement (CCD) credit" . "17")
    ("ACH demand cash concentration/disbursement (CCD) debit" . "18")
    ("ACH demand corporate trade payment (CTP) credit" . "19")
    ("Cheque" . "20") ("Banker's draft" . "21")
    ("Certified banker's draft" . "22")
    ("Bank cheque (issued by a banking or similar establishment)" . "23")
    ("Bill of exchange awaiting acceptance" . "24") ("Certified cheque" . "25")
    ("Local cheque" . "26")
    ("ACH demand corporate trade payment (CTP) debit" . "27")
    ("ACH demand corporate trade exchange (CTX) credit" . "28")
    ("ACH demand corporate trade exchange (CTX) debit" . "29")
    ("Credit transfer" . "30") ("Debit transfer" . "31")
    ("ACH demand cash concentration/disbursement plus (CCD+) credit" . "32")
    ("ACH demand cash concentration/disbursement plus (CCD+) debit" . "33")
    ("ACH prearranged payment and deposit (PPD)" . "34")
    ("ACH savings cash concentration/disbursement (CCD) credit" . "35")
    ("ACH savings cash concentration/disbursement (CCD) debit" . "36")
    ("ACH savings corporate trade payment (CTP) credit" . "37")
    ("ACH savings corporate trade payment (CTP) debit" . "38")
    ("ACH savings corporate trade exchange (CTX) credit" . "39")
    ("ACH savings corporate trade exchange (CTX) debit" . "40")
    ("ACH savings cash concentration/disbursement plus (CCD+) credit" . "41")
    ("Payment to bank account" . "42")
    ("ACH savings cash concentration/disbursement plus (CCD+) debit" . "43")
    ("Accepted bill of exchange" . "44")
    ("Referenced home-banking credit transfer" . "45")
    ("Interbank debit transfer" . "46") ("Home-banking debit transfer" . "47")
    ("Bank card" . "48") ("Direct debit" . "49") ("Payment by postgiro" . "50")
    ("FR, norme 6 97-Telereglement CFONB (French Organisation for" . "51")
    ("Urgent commercial payment" . "52") ("Urgent Treasury Payment" . "53")
    ("Credit card" . "54") ("Debit card" . "55") ("Bankgiro" . "56")
    ("Standing agreement" . "57") ("SEPA credit transfer" . "58")
    ("SEPA direct debit" . "59") ("Promissory note" . "60")
    ("Promissory note signed by the debtor" . "61")
    ("Promissory note signed by the debtor and endorsed by a bank" . "62")
    ("Promissory note signed by the debtor and endorsed by a third party"
     . "63")
    ("Promissory note signed by a bank" . "64")
    ("Promissory note signed by a bank and endorsed by another bank" . "65")
    ("Promissory note signed by a third party" . "66")
    ("Promissory note signed by a third party and endorsed by a bank" . "67")
    ("Online payment service" . "68")
    ("Bill drawn by the creditor on the debtor" . "70")
    ("Bill drawn by the creditor on a bank" . "74")
    ("Bill drawn by the creditor, endorsed by another bank" . "75")
    ("Bill drawn by the creditor on a bank and endorsed by a third party"
     . "76")
    ("Bill drawn by the creditor on a third party" . "77")
    ("Bill drawn by creditor on third party, accepted and endorsed by bank"
     . "78")
    ("Not transferable banker's draft" . "91")
    ("Not transferable local cheque" . "92") ("Reference giro" . "93")
    ("Urgent giro" . "94") ("Free format giro" . "95")
    ("Requested method for payment was not used" . "96")
    ("Clearing between partners" . "97") ("Mutually defined" . "ZZZ")))

(EXPORT '|Payment means code (UNCL4461)| :PEPPOL/CODE-LISTS)