(IN-PACKAGE :PEPPOL/CODE-LISTS)

(DEFVAR |UN/ECE Recommendation 21|
  '(("Drum, steel" . "1A") ("Drum, aluminium" . "1B") ("Drum, plywood" . "1D")
    ("Container, flexible" . "1F") ("Drum, fibre" . "1G")
    ("Drum, wooden" . "1W") ("Barrel, wooden" . "2C")
    ("Jerrican, steel" . "3A") ("Jerrican, plastic" . "3H")
    ("Bag, super bulk" . "43") ("Bag, polybag" . "44") ("Box, steel" . "4A")
    ("Box, aluminium" . "4B") ("Box, natural wood" . "4C")
    ("Box, plywood" . "4D") ("Box, reconstituted wood" . "4F")
    ("Box, fibreboard" . "4G") ("Box, plastic" . "4H")
    ("Bag, woven plastic" . "5H") ("Bag, textile" . "5L") ("Bag, paper" . "5M")
    ("Composite packaging, plastic receptacle" . "6H")
    ("Composite packaging, glass receptacle" . "6P") ("Case, car" . "7A")
    ("Case, wooden" . "7B") ("Pallet, wooden" . "8A") ("Crate, wooden" . "8B")
    ("Bundle, wooden" . "8C")
    ("Intermediate bulk container, rigid plastic" . "AA")
    ("Receptacle, fibre" . "AB") ("Receptacle, paper" . "AC")
    ("Receptacle, wooden" . "AD") ("Aerosol" . "AE")
    ("Pallet, modular, collars 80cms * 60cms" . "AF")
    ("Pallet, shrinkwrapped" . "AG") ("Pallet, 100cms * 110cms" . "AH")
    ("Clamshell" . "AI") ("Cone" . "AJ") ("Ball" . "AL")
    ("Ampoule, non-protected" . "AM") ("Ampoule, protected" . "AP")
    ("Atomizer" . "AT") ("Capsule" . "AV") ("Belt" . "B4") ("Barrel" . "BA")
    ("Bobbin" . "BB") ("Bottlecrate / bottlerack" . "BC") ("Board" . "BD")
    ("Bundle" . "BE") ("Balloon, non-protected" . "BF") ("Bag" . "BG")
    ("Bunch" . "BH") ("Bin" . "BI") ("Bucket" . "BJ") ("Basket" . "BK")
    ("Bale, compressed" . "BL") ("Basin" . "BM")
    ("Bale, non-compressed" . "BN")
    ("Bottle, non-protected, cylindrical" . "BO") ("Balloon, protected" . "BP")
    ("Bottle, protected cylindrical" . "BQ") ("Bar" . "BR")
    ("Bottle, non-protected, bulbous" . "BS") ("Bolt" . "BT") ("Butt" . "BU")
    ("Bottle, protected bulbous" . "BV") ("Box, for liquids" . "BW")
    ("Box" . "BX") ("Board, in bundle/bunch/truss" . "BY")
    ("Bars, in bundle/bunch/truss" . "BZ") ("Can, rectangular" . "CA")
    ("Crate, beer" . "CB") ("Churn" . "CC")
    ("Can, with handle and spout" . "CD") ("Creel" . "CE") ("Coffer" . "CF")
    ("Cage" . "CG") ("Chest" . "CH") ("Canister" . "CI") ("Coffin" . "CJ")
    ("Cask" . "CK") ("Coil" . "CL") ("Card" . "CM")
    ("Container, not otherwise specified as transport equipment" . "CN")
    ("Carboy, non-protected" . "CO") ("Carboy, protected" . "CP")
    ("Cartridge" . "CQ") ("Crate" . "CR") ("Case" . "CS") ("Carton" . "CT")
    ("Cup" . "CU") ("Cover" . "CV") ("Cage, roll" . "CW")
    ("Can, cylindrical" . "CX") ("Cylinder" . "CY") ("Canvas" . "CZ")
    ("Crate, multiple layer, plastic" . "DA")
    ("Crate, multiple layer, wooden" . "DB")
    ("Crate, multiple layer, cardboard" . "DC")
    ("Cage, Commonwealth Handling Equipment Pool (CHEP)" . "DG")
    ("Box, Commonwealth Handling Equipment Pool (CHEP), Eurobox" . "DH")
    ("Drum, iron" . "DI") ("Demijohn, non-protected" . "DJ")
    ("Crate, bulk, cardboard" . "DK") ("Crate, bulk, plastic" . "DL")
    ("Crate, bulk, wooden" . "DM") ("Dispenser" . "DN")
    ("Demijohn, protected" . "DP") ("Drum" . "DR")
    ("Tray, one layer no cover, plastic" . "DS")
    ("Tray, one layer no cover, wooden" . "DT")
    ("Tray, one layer no cover, polystyrene" . "DU")
    ("Tray, one layer no cover, cardboard" . "DV")
    ("Tray, two layers no cover, plastic tray" . "DW")
    ("Tray, two layers no cover, wooden" . "DX")
    ("Tray, two layers no cover, cardboard" . "DY") ("Bag, plastic" . "EC")
    ("Case, with pallet base" . "ED") ("Case, with pallet base, wooden" . "EE")
    ("Case, with pallet base, cardboard" . "EF")
    ("Case, with pallet base, plastic" . "EG")
    ("Case, with pallet base, metal" . "EH") ("Case, isothermic" . "EI")
    ("Envelope" . "EN") ("Flexibag" . "FB") ("Crate, fruit" . "FC")
    ("Crate, framed" . "FD") ("Flexitank" . "FE") ("Firkin" . "FI")
    ("Flask" . "FL") ("Footlocker" . "FO") ("Filmpack" . "FP") ("Frame" . "FR")
    ("Foodtainer" . "FT") ("Cart, flatbed" . "FW")
    ("Bag, flexible container" . "FX") ("Bottle, gas" . "GB") ("Girder" . "GI")
    ("Container, gallon" . "GL") ("Receptacle, glass" . "GR")
    ("Tray, containing horizontally stacked flat items" . "GU")
    ("Bag, gunny" . "GY") ("Girders, in bundle/bunch/truss" . "GZ")
    ("Basket, with handle, plastic" . "HA")
    ("Basket, with handle, wooden" . "HB")
    ("Basket, with handle, cardboard" . "HC") ("Hogshead" . "HG")
    ("Hanger" . "HN") ("Hamper" . "HR") ("Package, display, wooden" . "IA")
    ("Package, display, cardboard" . "IB") ("Package, display, plastic" . "IC")
    ("Package, display, metal" . "ID") ("Package, show" . "IE")
    ("Package, flow" . "IF") ("Package, paper wrapped" . "IG")
    ("Drum, plastic" . "IH")
    ("Package, cardboard, with bottle grip-holes" . "IK")
    ("Tray, rigid, lidded stackable (CEN TS 14482:2002)" . "IL")
    ("Ingot" . "IN") ("Ingots, in bundle/bunch/truss" . "IZ")
    ("Bag, jumbo" . "JB") ("Jerrican, rectangular" . "JC") ("Jug" . "JG")
    ("Jar" . "JR") ("Jutebag" . "JT") ("Jerrican, cylindrical" . "JY")
    ("Keg" . "KG") ("Kit" . "KI") ("Luggage" . "LE") ("Log" . "LG")
    ("Lot" . "LT") ("Lug" . "LU") ("Liftvan" . "LV")
    ("Logs, in bundle/bunch/truss" . "LZ") ("Crate, metal" . "MA")
    ("Bag, multiply" . "MB") ("Crate, milk" . "MC") ("Container, metal" . "ME")
    ("Receptacle, metal" . "MR") ("Sack, multi-wall" . "MS") ("Mat" . "MT")
    ("Receptacle, plastic wrapped" . "MW") ("Matchbox" . "MX")
    ("Not available" . "NA") ("Unpacked or unpackaged" . "NE")
    ("Unpacked or unpackaged, single unit" . "NF")
    ("Unpacked or unpackaged, multiple units" . "NG") ("Nest" . "NS")
    ("Net" . "NT") ("Net, tube, plastic" . "NU") ("Net, tube, textile" . "NV")
    ("Pallet, CHEP 40 cm x 60 cm" . "OA")
    ("Pallet, CHEP 80 cm x 120 cm" . "OB")
    ("Pallet, CHEP 100 cm x 120 cm" . "OC") ("Pallet, AS 4068-1993" . "OD")
    ("Pallet, ISO T11" . "OE")
    ("Platform, unspecified weight or dimension" . "OF") ("Block" . "OK")
    ("Octabin" . "OT") ("Container, outer" . "OU") ("Pan" . "P2")
    ("Packet" . "PA") ("Pallet, box Combined open-ended box and pallet" . "PB")
    ("Parcel" . "PC") ("Pallet, modular, collars 80cms * 100cms" . "PD")
    ("Pallet, modular, collars 80cms * 120cms" . "PE") ("Pen" . "PF")
    ("Plate" . "PG") ("Pitcher" . "PH") ("Pipe" . "PI") ("Punnet" . "PJ")
    ("Package" . "PK") ("Pail" . "PL") ("Plank" . "PN") ("Pouch" . "PO")
    ("Piece" . "PP") ("Receptacle, plastic" . "PR") ("Pot" . "PT")
    ("Tray" . "PU") ("Pipes, in bundle/bunch/truss" . "PV") ("Pallet" . "PX")
    ("Plates, in bundle/bunch/truss" . "PY")
    ("Planks, in bundle/bunch/truss" . "PZ")
    ("Drum, steel, non-removable head" . "QA")
    ("Drum, steel, removable head" . "QB")
    ("Drum, aluminium, non-removable head" . "QC")
    ("Drum, aluminium, removable head" . "QD")
    ("Drum, plastic, non-removable head" . "QF")
    ("Drum, plastic, removable head" . "QG")
    ("Barrel, wooden, bung type" . "QH")
    ("Barrel, wooden, removable head" . "QJ")
    ("Jerrican, steel, non-removable head" . "QK")
    ("Jerrican, steel, removable head" . "QL")
    ("Jerrican, plastic, non-removable head" . "QM")
    ("Jerrican, plastic, removable head" . "QN")
    ("Box, wooden, natural wood, ordinary" . "QP")
    ("Box, wooden, natural wood, with sift proof walls" . "QQ")
    ("Box, plastic, expanded" . "QR") ("Box, plastic, solid" . "QS")
    ("Rod" . "RD") ("Ring" . "RG") ("Rack, clothing hanger" . "RJ")
    ("Rack" . "RK") ("Reel" . "RL") ("Roll" . "RO") ("Rednet" . "RT")
    ("Rods, in bundle/bunch/truss" . "RZ") ("Sack" . "SA") ("Slab" . "SB")
    ("Crate, shallow" . "SC") ("Spindle" . "SD") ("Sea-chest" . "SE")
    ("Sachet" . "SH") ("Skid" . "SI") ("Case, skeleton" . "SK")
    ("Slipsheet" . "SL") ("Sheetmetal" . "SM") ("Spool" . "SO")
    ("Sheet, plastic wrapping" . "SP") ("Case, steel" . "SS") ("Sheet" . "ST")
    ("Suitcase" . "SU") ("Envelope, steel" . "SV") ("Shrinkwrapped" . "SW")
    ("Sleeve" . "SY") ("Sheets, in bundle/bunch/truss" . "SZ")
    ("Tablet" . "T1") ("Tub" . "TB") ("Tea-chest" . "TC")
    ("Tube, collapsible" . "TD") ("Tyre" . "TE")
    ("Tank container, generic" . "TG") ("Tierce" . "TI")
    ("Tank, rectangular" . "TK") ("Tub, with lid" . "TL") ("Tin" . "TN")
    ("Tun" . "TO") ("Trunk" . "TR") ("Truss" . "TS") ("Bag, tote" . "TT")
    ("Tube" . "TU") ("Tube, with nozzle" . "TV") ("Pallet, triwall" . "TW")
    ("Tank, cylindrical" . "TY") ("Tubes, in bundle/bunch/truss" . "TZ")
    ("Uncaged" . "UC") ("Unit" . "UN") ("Vat" . "VA")
    ("Bulk, gas (at 1031 mbar and 15°C)" . "VG") ("Vial" . "VI")
    ("Vanpack" . "VK") ("Bulk, liquid" . "VL")
    ("Bulk, solid, large particles (“nodules”)" . "VO")
    ("Vacuum-packed" . "VP")
    ("Bulk, liquefied gas (at abnormal temperature/pressure)" . "VQ")
    ("Vehicle" . "VN") ("Bulk, solid, granular particles (“grains”)" . "VR")
    ("Bulk, scrap metal" . "VS")
    ("Bulk, solid, fine particles (“powders”)" . "VY")
    ("Intermediate bulk container" . "WA") ("Wickerbottle" . "WB")
    ("Intermediate bulk container, steel" . "WC")
    ("Intermediate bulk container, aluminium" . "WD")
    ("Intermediate bulk container, metal" . "WF")
    ("Intermediate bulk container, steel, pressurised > 10 kpa" . "WG")
    ("Intermediate bulk container, aluminium, pressurised > 10 kpa" . "WH")
    ("Intermediate bulk container, metal, pressure 10 kpa" . "WJ")
    ("Intermediate bulk container, steel, liquid" . "WK")
    ("Intermediate bulk container, aluminium, liquid" . "WL")
    ("Intermediate bulk container, metal, liquid" . "WM")
    ("Intermediate bulk container, woven plastic, without coat/liner" . "WN")
    ("Intermediate bulk container, woven plastic, coated" . "WP")
    ("Intermediate bulk container, woven plastic, with liner" . "WQ")
    ("Intermediate bulk container, woven plastic, coated and liner" . "WR")
    ("Intermediate bulk container, plastic film" . "WS")
    ("Intermediate bulk container, textile with out coat/liner" . "WT")
    ("Intermediate bulk container, natural wood, with inner liner" . "WU")
    ("Intermediate bulk container, textile, coated" . "WV")
    ("Intermediate bulk container, textile, with liner" . "WW")
    ("Intermediate bulk container, textile, coated and liner" . "WX")
    ("Intermediate bulk container, plywood, with inner liner" . "WY")
    ("Intermediate bulk container, reconstituted wood, with inner liner"
     . "WZ")
    ("Bag, woven plastic, without inner coat/liner" . "XA")
    ("Bag, woven plastic, sift proof" . "XB")
    ("Bag, woven plastic, water resistant" . "XC")
    ("Bag, plastics film" . "XD")
    ("Bag, textile, without inner coat/liner" . "XF")
    ("Bag, textile, sift proof" . "XG")
    ("Bag, textile, water resistant" . "XH") ("Bag, paper, multi-wall" . "XJ")
    ("Bag, paper, multi-wall, water resistant" . "XK")
    ("Composite packaging, plastic receptacle in steel drum" . "YA")
    ("Composite packaging, plastic receptacle in steel crate box" . "YB")
    ("Composite packaging, plastic receptacle in aluminium drum" . "YC")
    ("Composite packaging, plastic receptacle in aluminium crate" . "YD")
    ("Composite packaging, plastic receptacle in wooden box" . "YF")
    ("Composite packaging, plastic receptacle in plywood drum" . "YG")
    ("Composite packaging, plastic receptacle in plywood box" . "YH")
    ("Composite packaging, plastic receptacle in fibre drum" . "YJ")
    ("Composite packaging, plastic receptacle in fibreboard box" . "YK")
    ("Composite packaging, plastic receptacle in plastic drum" . "YL")
    ("Composite packaging, plastic receptacle in solid plastic box" . "YM")
    ("Composite packaging, glass receptacle in steel drum" . "YN")
    ("Composite packaging, glass receptacle in steel crate box" . "YP")
    ("Composite packaging, glass receptacle in aluminium drum" . "YQ")
    ("Composite packaging, glass receptacle in aluminium crate" . "YR")
    ("Composite packaging, glass receptacle in wooden box" . "YS")
    ("Composite packaging, glass receptacle in plywood drum" . "YT")
    ("Composite packaging, glass receptacle in wickerwork hamper" . "YV")
    ("Composite packaging, glass receptacle in fibre drum" . "YW")
    ("Composite packaging, glass receptacle in fibreboard box" . "YX")
    ("Composite packaging, glass receptacle in expandable plastic pack" . "YY")
    ("Composite packaging, glass receptacle in solid plastic pack" . "YZ")
    ("Intermediate bulk container, paper, multi-wall" . "ZA")
    ("Bag, large" . "ZB")
    ("Intermediate bulk container, paper, multi-wall, water resistant" . "ZC")
    ("Intermediate bulk container, rigid plastic, with structural equipment, solids"
     . "ZD")
    ("Intermediate bulk container, rigid plastic, freestanding, solids" . "ZF")
    ("Intermediate bulk container, rigid plastic, with structural equipment,
            pressurised"
     . "ZG")
    ("Intermediate bulk container, rigid plastic, freestanding, pressurised"
     . "ZH")
    ("Intermediate bulk container, rigid plastic, with structural equipment, liquids"
     . "ZJ")
    ("Intermediate bulk container, rigid plastic, freestanding, liquids"
     . "ZK")
    ("Intermediate bulk container, composite, rigid plastic, solids" . "ZL")
    ("Intermediate bulk container, composite, flexible plastic, solids" . "ZM")
    ("Intermediate bulk container, composite, rigid plastic, pressurised"
     . "ZN")
    ("Intermediate bulk container, composite, flexible plastic, pressurised"
     . "ZP")
    ("Intermediate bulk container, composite, rigid plastic, liquids" . "ZQ")
    ("Intermediate bulk container, composite, flexible plastic, liquids"
     . "ZR")
    ("Intermediate bulk container, composite" . "ZS")
    ("Intermediate bulk container, fibreboard" . "ZT")
    ("Intermediate bulk container, flexible" . "ZU")
    ("Intermediate bulk container, metal, other than steel" . "ZV")
    ("Intermediate bulk container, natural wood" . "ZW")
    ("Intermediate bulk container, plywood" . "ZX")
    ("Intermediate bulk container, reconstituted wood" . "ZY")
    ("Mutually defined" . "ZZ") NIL))

(EXPORT '|UN/ECE Recommendation 21| :PEPPOL/CODE-LISTS)